#!/usr/bin/env bash
# Open up test desktop notification
# Based on http://cheesehead-techblog.blogspot.ca/2012/07/dbus-tutorial-intro-and-resources.html

dest="org.freedesktop.Notifications"
path="/org/freedesktop/Notifications"
method="org.freedesktop.Notifications.Notify"

app_name="2do"
id=""
icon="/home/eyqs/Dropbox/Projects/2do/"
summary="Take a break!"
body=""
actions=""
hints=""
timeout=0       # No timeout, must be manually dismissed

# Open up test desktop notification
dbus-send --session --dest="$dest" "$path" "$method" \
          string:"$app_name" uint32:$id string:"$icon""orange.gif" \
          string:"$summary" string:"$body" \
          array:string:"$actions" array:string:"$hints" int32:$timeout
