#!/usr/bin/env bash
# Manage various desktop notifications of periodic tasks

opt=$1
val=$2

dest="org.freedesktop.Notifications"
path="/org/freedesktop/Notifications"
method="org.freedesktop.Notifications.Notify"
iconpath="/home/eyqs/Dropbox/Projects/2do/"
app_name="2do"
id=""
actions=""
hints=""
timeout=0       # No timeout, everything manually dismissed

# Time to take a break, called by 2do.timer
if [ "$opt" = "--break" ]; then
    summary="Take a break!"
    body="Rest your eyes for 10 minutes."
    icon="$iconpath""orange.gif"

# Laptop battery getting low, called by lowbattery.timer
elif [ "$opt" = "--lowbattery" ]; then
    summary="Low battery!"
    body="Battery at "$2"%, connect charger."
    icon="$iconpath""red.gif"
fi

dbus-send --session --dest="$dest" "$path" "$method" \
          string:"$app_name" uint32:$id string:"$icon" \
          string:"$summary" string:"$body" \
          array:string:"$actions" array:string:"$hints" int32:$timeout

