#!/usr/bin/env bash
# Manage various desktop notifications of periodic tasks

opt=$1
val=$2

dest="org.freedesktop.Notifications"
path="/org/freedesktop/Notifications"
method="org.freedesktop.Notifications.Notify"
iconpath="/home/eyqs/Dropbox/Projects/2do/"
app_name="2do"
id=""
actions=""
hints=""
timeout=0       # No timeout, everything manually dismissed

# Time to take a break, called by systemd/user/30min.timer
if [ "$opt" = "--break" ]; then
    summary="Take a break!"
    body="Rest your eyes for 5 minutes."
    icon="$iconpath""orange.gif"

# Time for daily tasks, called by systemd/user/2do.timer
elif [ "$opt" = "--daily" ]; then
    summary="Keep that StackExchange streak!"
    body="Automatically opening all tabs in 300 seconds.
Terminate with 'killall python'."
    icon="$iconpath""yellow.gif"

# Laptop battery getting low, called by bin/lowbattery
elif [ "$opt" = "--lowbattery" ]; then
    summary="Low battery!"
    body="Battery at "$val"%, connect charger."
    icon="$iconpath""red.gif"

fi

dbus-send --session --dest="$dest" "$path" "$method" \
          string:"$app_name" uint32:$id string:"$icon" \
          string:"$summary" string:"$body" \
          array:string:"$actions" array:string:"$hints" int32:$timeout

if [ "$opt" = "--daily" ]; then
    /home/eyqs/Dropbox/Projects/2do/web.py
fi
